### ISSUE TITLE
Bug: add `float` to storage

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [yeagerai/genvm#156]
please add to docs

![Uploading image.png…]()

**Comment by kp2pml30** [comment]
Python `float`s and simple operations with them should be available anywhere (except for calldata)

np.float64 was a workaround I proposed before I fix this. Unfortunately I forgot to fix it ;)

**Comment by AgustinRamiroDiaz** [comment]
@kp2pml30 please also add docs for:
- what things are restricted to be `calldata`: I'm guessing it's function parameters and return types, from functions that are exposed via `@gl....`
- what types can be `calldata`: like int, bool...

**Comment by kp2pml30** [comment]
It is (and was) documented in the calldata module
