### ISSUE TITLE
Docs: Some `Bases` are not in the docs

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [yeagerai/genvm#157]
We can see sometimes

`Bases: WithStorageSlot, MutableSequence, Generic`

Yet they are not published in the docs. This is confusing

**Comment by kp2pml30** [comment]
[Generic](https://docs.python.org/3/library/typing.html#typing.Generic) and [MutableSequence](https://docs.python.org/3/library/collections.abc.html#collections.abc.MutableSequence) are from python stdlib
